export const allErrors = {
    ERROR_EMPTY_USER: 'ERROR_EMPTY_USER',

    ERROR_USERAPP_GETAUTHTOKEN_INVALID_USERNAME_OR_PASSWORD: 'ERROR_USERAPP_GETAUTHTOKEN_INVALID_USERNAME_OR_PASSWORD',

    ERROR_USER_USERNAME_IN_USE: 'ERROR_USER_USERNAME_IN_USE',
    ERROR_USER_EMAIL_IN_USE: 'ERROR_USER_EMAIL_IN_USE'
};

export default allErrors;
