export default {
    ERROR_EMPTY_USER: 'ERROR_EMPTY_USER',

    ERROR_USERAPP_GETAUTHTOKEN_INVALID_USERNAME_OR_PASSWORD: 'ERROR_USERAPP_GETAUTHTOKEN_INVALID_USERNAME_OR_PASSWORD',

    ERROR_USER_USERNAME_IN_USE: 'ERROR_USER_USERNAME_IN_USE',
    ERROR_USER_EMAIL_IN_USE: 'ERROR_USER_EMAIL_IN_USE',

    ERROR_USER_EMAIL_REQUIRED: 'ERROR_USER_EMAIL_REQUIRED',
    ERROR_USER_EMAIL_INVALID: 'ERROR_USER_EMAIL_INVALID',

    ERROR_USER_USERNAME_REQUIRED: 'ERROR_USER_USERNAME_REQUIRED',
    ERROR_USER_USERNAME_MINLENGTH: 'ERROR_USER_USERNAME_MINLENGTH',
    ERROR_USER_USERNAME_MAXLENGTH: 'ERROR_USER_USERNAME_MAXLENGTH',

    ERROR_USER_PASSWORD_MINLENGTH: 'ERROR_USER_PASSWORD_MINLENGTH',
    ERROR_USER_PASSWORD_MAXLENGTH: 'ERROR_USER_PASSWORD_MAXLENGTH',

    ERRORS_AUTHENTICATEUSERFORM_PASSWORD_REQUIRED: 'ERRORS_AUTHENTICATEUSERFORM_PASSWORD_REQUIRED'
};
